import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from './context/AuthContext'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html className='scrollable-element' id='htmx' lang="en" style={{ backgroundColor: "black" , scrollbarColor:"red yellow"}}>
        <body className={inter.className}>
        <AuthContextProvider>
          <Navbar />
          {children}
      </AuthContextProvider>
    </body>
    </html >
  )
}
